#!/usr/bin/env python3
"""
Goodix SecWhiteEncrypt - exact verified implementation.

Reverse-engineered from Wbdi.dll (SecWhiteEncrypt @ 0x180005f30, seccipher.c).
See RE_WHITEBOX_EXACT.md for full disassembly notes.

Algorithm:
  1. nonce = LE32(len(psk))
  2. hash1 = SHA256(nonce + "123GOODIX")
  3. prefix = hash1[0:16] with byte 15 low nibble replaced by len(psk) & 0x0F
  4. hash2 = SHA256(prefix + zeros(48) + WB_CONSTANT)
  5. AES key = hash2[0:16], IV = prefix
  6. ciphertext = AES-128-CBC-PKCS7(key, iv, psk)
  7. hmac_tag = HMAC-SHA256(key=hash2, data=ciphertext)
  8. output = prefix(16) + ciphertext + hmac_tag(32)

Known test vector (verified):
  Input:  PSK = 32 zero bytes
  Output: ec35ae3abb45ed3f12c4751f1e5c2cc05b3c5452e9104d9f2a3118644f37a04b
          6fd66b1d97cf80f1345f76c84f03ff30bb51bf308f2a9875c41e6592cd2a2f9e
          60809b17b5316037b69bb2fa5d4c8ac31edb3394046ec06bbdacc57da6a756c5
  (96 bytes total)
"""

import hashlib
import hmac
import struct
from cryptography.hazmat.primitives.ciphers import Cipher, algorithms, modes
from cryptography.hazmat.primitives import padding as crypto_padding


WB_SALT = b"123GOODIX"

# Fixed 16-byte constant generated by the whitebox init function (fcn.1800085e0).
# Derived from rotated "Goodix" ASCII bytes through SHA-256/CRC-32/AES-round
# operations. Extracted via Unicorn emulation of the DLL function.
WB_CONSTANT = bytes.fromhex("5cba6e25819518de2d53e96dc0347ab0")

# Known test vector
KNOWN_PSK = bytes(32)
KNOWN_OUTPUT = bytes.fromhex(
    "ec35ae3abb45ed3f12c4751f1e5c2cc05b3c5452e9104d9f2a3118644f37a04b"
    "6fd66b1d97cf80f1345f76c84f03ff30bb51bf308f2a9875c41e6592cd2a2f9e"
    "60809b17b5316037b69bb2fa5d4c8ac31edb3394046ec06bbdacc57da6a756c5"
)


def sec_white_encrypt(psk: bytes) -> bytes:
    """
    Exact replica of SecWhiteEncrypt from Wbdi.dll.

    Args:
        psk: Plaintext data to encrypt (typically 32-byte PSK).

    Returns:
        Encrypted output: prefix(16) + ciphertext + HMAC(32).
        For 32-byte input, output is 96 bytes.
    """
    data_len = len(psk)

    # Step 1: nonce = little-endian 4-byte encoding of input length
    nonce = struct.pack('<I', data_len)

    # Step 2: hash1 = SHA256(nonce || "123GOODIX")
    hash1 = hashlib.sha256(nonce + WB_SALT).digest()

    # Step 3: modify byte 15 - replace low nibble with len & 0x0F
    prefix = bytearray(hash1[:16])
    prefix[15] = (prefix[15] & 0xF0) | (data_len & 0x0F)
    prefix = bytes(prefix)

    # Step 4: hash2 = SHA256(prefix + zeros(48) + WB_CONSTANT)
    hash2 = hashlib.sha256(prefix + bytes(48) + WB_CONSTANT).digest()

    # Step 5: AES-128-CBC encrypt with PKCS7 padding
    aes_key = hash2[:16]
    iv = prefix
    padder = crypto_padding.PKCS7(128).padder()
    padded = padder.update(psk) + padder.finalize()
    enc = Cipher(algorithms.AES(aes_key), modes.CBC(iv)).encryptor()
    ct = enc.update(padded) + enc.finalize()

    # Step 6: HMAC-SHA256(key=full_hash2, data=ciphertext)
    mac = hmac.new(hash2, ct, hashlib.sha256).digest()

    # Step 7: output = prefix(16) + ciphertext + hmac(32)
    return prefix + ct + mac


def sec_white_decrypt(encrypted: bytes, expected_len: int = 32) -> bytes:
    """
    Decrypt SecWhiteEncrypt output back to the original PSK.

    This reverses the encryption by:
    1. Parsing the prefix, ciphertext, and HMAC from the encrypted blob
    2. Recomputing the key derivation from the prefix
    3. Verifying the HMAC
    4. Decrypting with AES-128-CBC

    Args:
        encrypted: The SecWhiteEncrypt output blob.
        expected_len: Expected plaintext length (default 32).

    Returns:
        Decrypted plaintext data.

    Raises:
        ValueError: If HMAC verification fails.
    """
    # Parse output format
    prefix = encrypted[:16]
    mac = encrypted[-32:]
    ct = encrypted[16:-32]

    # Recover data_len from prefix byte 15 low nibble
    data_len = prefix[15] & 0x0F
    # For lengths >= 16, we need the expected_len hint
    if expected_len > 15:
        data_len = expected_len

    # Recompute nonce and verify prefix
    nonce = struct.pack('<I', data_len)
    hash1 = hashlib.sha256(nonce + WB_SALT).digest()
    expected_prefix = bytearray(hash1[:16])
    expected_prefix[15] = (expected_prefix[15] & 0xF0) | (data_len & 0x0F)
    if bytes(expected_prefix) != prefix:
        raise ValueError(f"Prefix mismatch: expected {bytes(expected_prefix).hex()}, got {prefix.hex()}")

    # Recompute hash2 and verify HMAC
    hash2 = hashlib.sha256(prefix + bytes(48) + WB_CONSTANT).digest()
    expected_mac = hmac.new(hash2, ct, hashlib.sha256).digest()
    if not hmac.compare_digest(mac, expected_mac):
        raise ValueError("HMAC verification failed")

    # Decrypt
    aes_key = hash2[:16]
    iv = prefix
    dec = Cipher(algorithms.AES(aes_key), modes.CBC(iv)).decryptor()
    padded = dec.update(ct) + dec.finalize()

    # Remove PKCS7 padding
    unpadder = crypto_padding.PKCS7(128).unpadder()
    return unpadder.update(padded) + unpadder.finalize()


def test():
    """Verify against the known test vector."""
    print("=" * 70)
    print("SecWhiteEncrypt - Test")
    print("=" * 70)

    # Test encryption
    result = sec_white_encrypt(KNOWN_PSK)
    print(f"PSK (input):  {KNOWN_PSK.hex()}")
    print(f"Output:       {result.hex()}")
    print(f"Expected:     {KNOWN_OUTPUT.hex()}")
    print(f"Match:        {result == KNOWN_OUTPUT}")
    assert result == KNOWN_OUTPUT, "Encryption test FAILED!"
    print("Encryption: PASS")

    # Test decryption
    decrypted = sec_white_decrypt(KNOWN_OUTPUT, expected_len=32)
    print(f"\nDecrypted:    {decrypted.hex()}")
    print(f"Expected:     {KNOWN_PSK.hex()}")
    print(f"Match:        {decrypted == KNOWN_PSK}")
    assert decrypted == KNOWN_PSK, "Decryption test FAILED!"
    print("Decryption: PASS")

    # Test with a non-zero PSK
    test_psk = bytes.fromhex(
        "e8a8ddee11036e4992915d3cffbe7a299ae86e02dd1ff8eb3f813c75868329a7")
    wb = sec_white_encrypt(test_psk)
    print(f"\nNon-zero PSK: {test_psk.hex()}")
    print(f"Encrypted:    {wb.hex()} ({len(wb)} bytes)")

    # Verify round-trip
    rt = sec_white_decrypt(wb, expected_len=32)
    assert rt == test_psk, "Round-trip test FAILED!"
    print("Round-trip:   PASS")

    print("\n" + "=" * 70)
    print("ALL TESTS PASSED")
    print("=" * 70)


if __name__ == "__main__":
    test()
